// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherDataManagement.Api.Models;

namespace WeatherDataManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210122155624_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WeatherDataManagement.Models.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Temp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 48f,
                            Location = "Inne",
                            Temp = 24.5f
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 12f,
                            Location = "Inne",
                            Temp = 25.5f
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 34f,
                            Location = "Inne",
                            Temp = 14.5f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
